import type { Artist } from "@/components/ui/artist-card"
import type { Event } from "@/components/ui/event-card"

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "Elena Rodriguez",
    image: "/female-portrait-artist-painting-studio.jpg",
    artForms: ["Painter", "Sculptor"],
    region: "Barcelona, Spain",
    followers: 12500,
    isVerified: true,
  },
  {
    id: "2",
    name: "Marcus Chen",
    image: "/male-filmmaker-with-camera-cinematography.jpg",
    artForms: ["Filmmaker", "Photographer"],
    region: "Los Angeles, USA",
    followers: 8900,
    isVerified: true,
  },
  {
    id: "3",
    name: "Aisha Patel",
    image: "/female-dancer-classical-indian-dance.jpg",
    artForms: ["Dancer", "Choreographer"],
    region: "Mumbai, India",
    followers: 15200,
    isVerified: true,
  },
  {
    id: "4",
    name: "Johan Berg",
    image: "/male-musician-piano-concert-hall.jpg",
    artForms: ["Musician", "Composer"],
    region: "Stockholm, Sweden",
    followers: 6700,
    isVerified: false,
  },
  {
    id: "5",
    name: "Yuki Tanaka",
    image: "/female-ceramicist-pottery-artisan-craft.jpg",
    artForms: ["Ceramicist", "Artisan"],
    region: "Kyoto, Japan",
    followers: 9300,
    isVerified: true,
  },
  {
    id: "6",
    name: "Omar Hassan",
    image: "/male-calligrapher-arabic-art-studio.jpg",
    artForms: ["Calligrapher", "Visual Artist"],
    region: "Dubai, UAE",
    followers: 5400,
    isVerified: false,
  },
  {
    id: "7",
    name: "Sophie Laurent",
    image: "/female-fashion-designer-textile-art.jpg",
    artForms: ["Fashion Designer", "Textile Artist"],
    region: "Paris, France",
    followers: 11200,
    isVerified: true,
  },
  {
    id: "8",
    name: "David Okonkwo",
    image: "/male-sculptor-wood-carving-african-art.jpg",
    artForms: ["Sculptor", "Wood Carver"],
    region: "Lagos, Nigeria",
    followers: 7800,
    isVerified: true,
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Abstract Expressions: A Journey Through Color",
    image: "/art-exhibition-gallery-abstract-paintings.jpg",
    date: "Feb 15, 2026",
    time: "6:00 PM",
    location: "Modern Art Gallery, Barcelona",
    type: "event",
    artist: "Elena Rodriguez",
    attendees: 120,
    price: "€25",
  },
  {
    id: "2",
    title: "Documentary Filmmaking Masterclass",
    image: "/film-workshop-cinema-classroom.jpg",
    date: "Feb 20, 2026",
    time: "10:00 AM",
    location: "Film Institute, Los Angeles",
    type: "workshop",
    artist: "Marcus Chen",
    attendees: 45,
    price: "$150",
  },
  {
    id: "3",
    title: "Classical Kathak Performance",
    image: "/indian-classical-dance-performance-stage.jpg",
    date: "Feb 25, 2026",
    time: "7:30 PM",
    location: "National Theater, Mumbai",
    type: "premiere",
    artist: "Aisha Patel",
    attendees: 500,
    price: "₹1,200",
  },
  {
    id: "4",
    title: "Piano Concerto Night",
    image: "/piano-concert-classical-music-hall.jpg",
    date: "Mar 1, 2026",
    time: "8:00 PM",
    location: "Concert Hall, Stockholm",
    type: "event",
    artist: "Johan Berg",
    attendees: 300,
    price: "€45",
  },
  {
    id: "5",
    title: "Japanese Pottery Workshop",
    image: "/pottery-workshop-ceramics-hands-clay.jpg",
    date: "Mar 5, 2026",
    time: "2:00 PM",
    location: "Traditional Crafts Center, Kyoto",
    type: "workshop",
    artist: "Yuki Tanaka",
    attendees: 15,
    price: "¥8,000",
  },
  {
    id: "6",
    title: "Arabic Calligraphy for Beginners",
    image: "/calligraphy-workshop-arabic-art-writing.jpg",
    date: "Mar 10, 2026",
    time: "4:00 PM",
    location: "Cultural Center, Dubai",
    type: "workshop",
    artist: "Omar Hassan",
    attendees: 20,
    price: "AED 200",
  },
]

export const artFormCategories = [
  { id: "music", label: "Music", icon: "Music" },
  { id: "film", label: "Film & Video", icon: "Film" },
  { id: "dance", label: "Dance", icon: "Sparkles" },
  { id: "painting", label: "Painting", icon: "Palette" },
  { id: "sculpture", label: "Sculpture", icon: "Box" },
  { id: "crafts", label: "Crafts", icon: "Scissors" },
  { id: "photography", label: "Photography", icon: "Camera" },
  { id: "theater", label: "Theater", icon: "Drama" },
  { id: "writing", label: "Writing", icon: "PenTool" },
  { id: "fashion", label: "Fashion", icon: "Shirt" },
]

export const regions = ["All Regions", "North America", "Europe", "Asia", "Africa", "South America", "Oceania"]
